<?php
session_start();
require 'db.php';

// Validate session and input
if (!isset($_SESSION['user_id'])) {
    header('HTTP/1.1 401 Unauthorized');
    die("Error: Unauthorized access. Please log in.");
}

if (!isset($_GET['event_id'])) {
    header('HTTP/1.1 400 Bad Request');
    die("Error: Event ID not specified.");
}

// Sanitize input
$event_id = filter_var($_GET['event_id'], FILTER_VALIDATE_INT);
if ($event_id === false) {
    header('HTTP/1.1 400 Bad Request');
    die("Error: Invalid Event ID format.");
}

$user_id = $_SESSION['user_id'];

try {
    // Fetch event data - changed 'id' to 'event_id' to match your database
    $stmt = $pdo->prepare("SELECT * FROM events WHERE event_id = ? AND user_id = ?");
    $stmt->execute([$event_id, $user_id]);
    $event = $stmt->fetch();

    if (!$event) {
        header('HTTP/1.1 404 Not Found');
        die("Error: Event not found or you don't have permission to access it.");
    }

    // Format the download content
    $content = "================================\n";
    $content .= "EVENT DETAILS\n";
    $content .= "================================\n\n";
    
    $content .= "Title:       " . htmlspecialchars($event['event_type']) . "\n"; // Changed from 'title' to 'event_type'
    $content .= "Type:        " . htmlspecialchars(ucfirst($event['event_type'])) . "\n";
    $content .= "Host:        " . htmlspecialchars($event['host']) . "\n";
    $content .= "Venue:       " . htmlspecialchars($event['venue']) . "\n";
    $content .= "Date:        " . htmlspecialchars($event['event_date']) . "\n";
    $content .= "Time:        " . htmlspecialchars($event['start_time']) . " - " . htmlspecialchars($event['end_time']) . "\n\n";
    
    $content .= "Description:\n";
    $content .= wordwrap(htmlspecialchars($event['description']), 75, "\n") . "\n\n";
    
    $content .= "================================\n";
    $content .= "Generated by Event Planner\n";
    $content .= "Downloaded on: " . date('Y-m-d H:i:s') . "\n";
    $content .= "================================\n";

    // Create a safe filename
    $clean_title = preg_replace('/[^a-zA-Z0-9-_]/', '_', $event['event_type']); // Changed from 'title' to 'event_type'
    $filename = "Event_" . $clean_title . "_" . date('Ymd') . ".txt";

    // Set headers for download
    header('Content-Type: text/plain');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($content));
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');
    
    echo $content;
    exit;

} catch (PDOException $e) {
    error_log("Database error in download_event.php: " . $e->getMessage());
    header('HTTP/1.1 500 Internal Server Error');
    die("Error: Unable to process your request. Please try again later.");
}